# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "cheddargetter_client_rails"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Brent Wooden"]
  s.date = "2013-01-25"
  s.description = "Integrates CheddarGetter api with Active Record. Uses cheddargetter_client_ruby."
  s.email = "brent.wooden@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "cheddargetter_client_rails.gemspec",
    "features/cheddargetter_client_rails.feature",
    "features/step_definitions/cheddargetter_client_rails_steps.rb",
    "features/support/env.rb",
    "lib/cheddargetter_client_rails.rb",
    "lib/cheddargetter_client_rails/subscription.rb",
    "lib/generators/cheddargetter/USAGE",
    "lib/generators/cheddargetter/cheddargetter_generator.rb",
    "lib/generators/cheddargetter/templates/cheddargetter.yml",
    "lib/generators/cheddargetter/templates/cheddargetter_client.rb",
    "lib/rails/naming.rb",
    "lib/rails/record_identifier.rb",
    "spec/cheddargetter_client_rails/subscription_spec.rb",
    "spec/cheddargetter_client_rails_spec.rb",
    "spec/fixtures/users.yml",
    "spec/generator_spec.rb",
    "spec/naming_spec.rb",
    "spec/record_identifier_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/BrentW/cheddargetter_client_rails"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Integrates CheddarGetter api with Active Record"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 2.3.5"])
      s.add_runtime_dependency(%q<cheddargetter_client>, [">= 0.0.2"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_runtime_dependency(%q<cheddargetter_client>, [">= 0.0.2"])
    else
      s.add_dependency(%q<activesupport>, [">= 2.3.5"])
      s.add_dependency(%q<cheddargetter_client>, [">= 0.0.2"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<cheddargetter_client>, [">= 0.0.2"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 2.3.5"])
    s.add_dependency(%q<cheddargetter_client>, [">= 0.0.2"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<cheddargetter_client>, [">= 0.0.2"])
  end
end

