# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cheddargetter_client_rails}
  s.version = "0.1.15"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Brent Wooden"]
  s.date = %q{2011-05-15}
  s.description = %q{Integrates CheddarGetter api with Active Record. Uses cheddargetter_client_ruby.}
  s.email = %q{brent.wooden@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "cheddargetter_client_rails.gemspec",
    "features/cheddargetter_client_rails.feature",
    "features/step_definitions/cheddargetter_client_rails_steps.rb",
    "features/support/env.rb",
    "lib/cheddargetter_client_rails.rb",
    "lib/cheddargetter_client_rails/subscription.rb",
    "lib/generators/cheddargetter/USAGE",
    "lib/generators/cheddargetter/cheddargetter_generator.rb",
    "lib/generators/cheddargetter/templates/cheddargetter.yml",
    "lib/generators/cheddargetter/templates/cheddargetter_client.rb",
    "lib/rails/record_identifier.rb",
    "spec/cheddargetter_client_rails/subscription_spec.rb",
    "spec/cheddargetter_client_rails_spec.rb",
    "spec/fixtures/users.yml",
    "spec/generator_spec.rb",
    "spec/record_identifier_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/BrentW/cheddargetter_client_rails}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Integrates CheddarGetter api with Active Record}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 2.3.5"])
      s.add_runtime_dependency(%q<cheddargetter_client_ruby>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<activesupport>, [">= 2.3.5"])
      s.add_dependency(%q<cheddargetter_client_ruby>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 2.3.5"])
    s.add_dependency(%q<cheddargetter_client_ruby>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

